branch-defaults:
  main:
    environment: okta-crud-api-prod
  master:
    environment: okta-crud-api-prod
deploy:
  artifact: target/okta-springboot-api-0.0.1-SNAPSHOT.jar
global:
  application_name: okta-crud-api
  default_ec2_keyname: null
  default_platform: Corretto 21 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
