server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: okta-springboot-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/okta_products}
    username: ${SPRING_DATASOURCE_USERNAME:okta_user}
    password: ${SPRING_DATASOURCE_PASSWORD:okta_password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: ${OKTA_ISSUER}
